name: Build

on:
  # Trigger the workflow on pushes to only the 'main' branch (this avoids duplicate checks being run e.g., for dependabot pull requests)
  push:
    branches: [ main ]
  # Trigger the workflow on any pull request
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
          submodules: recursive

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.100"

      - name: Restore solution
        run: |
          dotnet restore
          dotnet tool restore

      - name: Build and pack solution
        run: |
          dotnet build -c Release
          dotnet pack -c Release --no-build

      - name: Upload thunderstore artifact
        uses: actions/upload-artifact@v4
        with:
          name: thunderstore-build
          path: |
            ./*/assets/thunderstore.toml.user
            ./*/bin/Release/*/dist/*.zip

      - name: Upload nupkg artifact
        uses: actions/upload-artifact@v4
        with:
          name: nupkg-build
          path: ./*/bin/Release/*.nupkg
